# Dockerfile.nodejs

# Utiliser une image Node.js
FROM node:latest

# Créer le répertoire de travail de l'application
WORKDIR /app/api

# Monter les fichiers package.json et package-lock.json depuis le système hôte
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers du projet
COPY . .

# Exposer le port sur lequel l'application écoutera
EXPOSE 3100

# Commande pour démarrer l'application en mode développement avec nodemon
CMD ["npm", "run", "dev"]
